#!/usr/bin/env python2

# Copyright (C) 2011-2012 by Imperial College London
# Copyright (C) 2013 University of Oxford
# Copyright (C) 2014 University of Edinburgh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, version 3 of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Based on burgers_newton.py test from dolfin-adjoint
# Code first added: 2012-10-25

from dolfin import *
from timestepping import *

import numpy

if "reorder_dofs_serial" in parameters:
  parameters["reorder_dofs_serial"] = False

ngrid = 30
nu = StaticConstant(0.0001)
dt = StaticConstant(0.05 / ngrid)
t_end = 0.2

mesh = UnitIntervalMesh(ngrid)
space = FunctionSpace(mesh, "CG", 2)
test, trial = TestFunction(space), TrialFunction(space)

ic = StaticFunction(space, name = "initial_condition")
ic.assign(project(Expression("sin(2.0 * pi * x[0])"), space))

system = TimeSystem()
levels   = TimeLevels(levels = [n - 2, n - 1, n, n + 1], cycle_map = {n - 2:n - 1, n - 1:n, n:n + 1})
levels_F = TimeLevels(levels = [n - 2, n - 1, n], cycle_map = {n - 2:n - 1, n - 1:n}, last_past_level = n - 1)
u = TimeFunction(levels,   space, name = "u")
F = TimeFunction(levels_F, space, name = "F")
def rhs(n):
  return - dt * (inner(test, dot(as_vector([u[n]]), grad(u[n]))) + nu * inner(grad(test), grad(u[n]))) * dx
def add_F_solve(n):
  system.add_solve(inner(test, trial) * dx == rhs(n),
    F[n],
    StaticDirichletBC(space, 0.0, "on_boundary"), solver_parameters = {"linear_solver":"lu"})
  return
  
system.add_solve(ic, u[-2])
add_F_solve(-2)
system.add_solve(inner(test, trial) * dx == inner(test, u[-2]) * dx + inner(test, F[-2]) * dx,
  u[-1],
  StaticDirichletBC(space, 0.0, "on_boundary"), solver_parameters = {"linear_solver":"lu"})
add_F_solve(-1)
system.add_solve(LinearCombination((1.5, F[-1]), (-0.5, F[-2]), (1.0, u[-1])), u[0])
add_F_solve(n)
system.add_solve(LinearCombination(((23.0 / 12.0), F[n]), \
                                   ((-4.0 / 3.0), F[n - 1]), \
                                   ((5.0 / 12.0), F[n - 2]), \
                                   (1.0, u[n])), u[n + 1])

system = system.assemble(adjoint = True, disk_period = 10)
t = 2.0 * float(dt)
while t <= t_end:
  system.timestep()
  t += float(dt)
system.finalise()

dolfin_adjoint_solution = numpy.array(map(float, """0.00000000e+00   9.18805579e-02   1.83759742e-01   2.73860166e-01
   3.61117034e-01   4.42519719e-01   5.13747010e-01   5.69016211e-01
   6.02621961e-01   6.10778903e-01   5.92895894e-01   5.51016985e-01
   4.87316764e-01   3.99651373e-01   2.71421856e-01  -5.36274503e-10
  -2.71421857e-01  -3.99651370e-01  -4.87316754e-01  -5.51016958e-01
  -5.92895835e-01  -6.10778810e-01  -6.02621790e-01  -5.69016086e-01
  -5.13747234e-01  -4.42520432e-01  -3.61116970e-01  -2.73860258e-01
  -1.83760441e-01  -9.18801399e-02   0.00000000e+00   4.67069887e-02
   1.39469520e-01   2.31986028e-01   3.24146253e-01   4.16283864e-01
   5.09502999e-01   6.05496425e-01   7.06191068e-01   8.12622635e-01
   9.23868675e-01   1.03651841e+00   1.14487768e+00   1.24116815e+00
   1.31415317e+00   1.34143201e+00  -1.34143201e+00  -1.31415317e+00
  -1.24116814e+00  -1.14487767e+00  -1.03651837e+00  -9.23868601e-01
  -8.12622488e-01  -7.06190884e-01  -6.05496402e-01  -5.09503523e-01
  -4.16284299e-01  -3.24145998e-01  -2.31986661e-01  -1.39469523e-01
  -4.67066570e-02""".split()))
err = abs(u[N].vector().array() - dolfin_adjoint_solution).max()
print(u[N].vector().array(), err)
assert(err < 5.0e-9)

system.verify_checkpoints()

system.set_functional(u[N] * u[N] * dx)
J = system.compute_functional()
grad = system.compute_gradient([ic, nu])
print(grad[0].array(), float(grad[1]))

orders = system.taylor_test(ic, J = J, grad = grad[0])
assert((orders > 1.99).all())

orders = system.taylor_test(nu, J = J, grad = grad[1])
assert((orders > 1.99).all())
