#!/usr/bin/env python

# Copyright (C) 2013 University of Oxford
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, version 3 of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import glob
import os
import subprocess
import sys

path = os.path.abspath(os.path.dirname(__file__))
tests = glob.glob(os.path.join(path, "*"))
tests.remove(os.path.abspath(__file__))

successes = 0
failures = []
for test in tests:
  print "Running test: %s" % test
  try:
    proc = subprocess.Popen(("%s" % test).split())
    proc.wait()
  except:
    raise Exception("Failed to run test: %s" % test)
  if proc.returncode == 0:
    print "Test success: %s" % test
    successes += 1
  else:
    sys.stderr.write("Test failure: %s\n" % test)
    failures.append(test)
print \
"""\
----------------------------------------------------------------------
Summary:

Successes: %i
Failures: %i""" % (successes, len(failures))
if len(failures) > 0:
  print "Failures:"
  for failure in failures:
    print failure
  sys.exit(1)
