#!/usr/bin/env python2

# Copyright (C) 2013 University of Oxford
# Copyright (C) 2014 University of Edinburgh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, version 3 of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from timestepping import *
from fractions import Fraction

# Create a TimeLevel with an offset of 2
n1 = TimeLevel(2)
# Create a TimeLevel with an offset of -1/2
n2 = TimeLevel(-Fraction(1, 2))  
# Create a FinalTimeLevel with an offset of 0
N1 = FinalTimeLevel()            

# Create a TimeLevel with an offset of 2
n3 = n + 2
# Create a TimeLevel with an offset of -3/2
n4 = n - Fraction(3, 2)

# Create a FinalTimeLevel with an offset of 1
N2 = N + 1

print(n1 == n2)  # False
print(n1 > n2)   # True
print(n1 == n3)  # True
print(n1 >= n3)  # True

print(N1 == N2)  # False
print(N1 <= N2)  # True

assert(not n1 == n2)
assert(n1 > n2)
assert(n1 == n3)
assert(n1 >= n3)

assert(not N1 == N2)
assert(N1 <= N2)