#!/usr/bin/env python

from dolfin import *
from timestepping import *

# A named Constant
c = Constant(1.0, name = "c")

# Define a simple structured mesh on the unit interval
mesh = UnitIntervalMesh(10)
# P1 function space
space = FunctionSpace(mesh, "CG", 1)
# A named Function
F = Function(space, name = "F")